### ISSUE TITLE
Unable to post Item in ERP

### ISSUE THREAD

**Issue by chechani** [laxmantandon/express_tally#2]
Hi,

Thanks for this fantastic utility. With this I was able to post Customer, Supplier in ERP.

I am using v14 of Frappe & ERPNext. and Tally Version is Prime 3.0.1

The issue is when I post item in ERP from Tally I am getting here as attached.

Please Note that I have already defined HSN code in all items in Tally
![Screenshot 2023-08-16 102737](https://github.com/laxmantandon/express_tally/assets/6291292/2aacb6a8-af4c-4efe-b979-457ce8f5f936)

Also Can you post some notes for Posting Sales, Purchase and Bank transactions

**Comment by chechani** [comment]
Its already installed

**Comment by ravaljay23** [comment]
Their many changes in How GST and it's related stuff are treated in Tally Prime after the release of the 3.0 version so the code must require some modification. Hoping someone will do asap.

**Comment by Veeramk** [comment]
This is still not working. Did anyone find a way to get the item posted?
