### ISSUE TITLE
Unable to Impot Tally data into ERPNEXT

### ISSUE THREAD

**Issue by chandrubiradar** [laxmantandon/express_tally#6]
![Screenshot (525)](https://github.com/laxmantandon/express_tally/assets/47516435/d6df301c-7e48-4633-8490-c6af5cda2f37)
![Screenshot (526)](https://github.com/laxmantandon/express_tally/assets/47516435/45f7488f-592c-46ed-b7b2-6d81d5514d75)

**Comment by laxmantandon** [comment]
Issue does not belong this application.
