### ISSUE TITLE
Mapping Tally Invoice Numbers to ERP Next Invoice Number

### ISSUE THREAD

**Issue by turqosoft** [laxmantandon/express_tally#7]
On migrating invoices from Tally to ERPNext, invoice numbers are created as per ERPNext Document naming series. So when we try to migrate payments data from Tally to ERPNext, they will fail.
How to overcome this situation?
Create Sales and Purchase invoices with the same invoice number as in Tally.
Thank You

**Comment by laxmantandon** [comment]
Hi,

You can create a custom field in Sales Invoice with name "tally_voucherno",
and set naming rule of Sales Invoice doctype "By fieldname", specify
"tally_voucherno" as field, this will resolve your issue.

Regards
Laxman

**Comment by turqosoft** [comment]
Thank You, that worked.
